[project]
name = "katzenpost_thinclient"
version = "0.0.24"
dependencies = [
    "cbor2>=5.6.5,<7",
    "coloredlogs~=15.0.1",
    "toml~=0.10.2",
]
authors = [
  { name="David Stainton", email="dstainton415@gmail.com" },
]
description = "A thinclient for the Katzenpost client daemon"
readme = "README_python.md"
requires-python = ">=3.10"
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
]

[project.urls]
Homepage = "https://katzenpost.network/"
Issues = "https://github.com/katzenpost/thin_client/issues"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "katzenpost_thinclient"

[project.optional-dependencies]
dev = [
    "mypy",
    "types-toml"
]
test = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-timeout",
    "pytest-xdist",
]

