# SPDX-License-Identifier: AGPL-3.0-only

when:
  event: [push, pull_request, manual]

steps:
  - name: test-python
    image: ${CI_IMAGE:-localhost/thinclient-ci:latest}
    commands:
      - make test-python

  - name: test-rust
    image: ${CI_IMAGE:-localhost/thinclient-ci:latest}
    commands:
      - make test-rust

  - name: check
    image: ${CI_IMAGE:-localhost/thinclient-ci:latest}
    commands:
      - make check
