name: Integration Tests with Docker Mixnet

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-integration-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout thinclient repository
        uses: actions/checkout@v4
        with:
          path: thinclient

      - name: Checkout katzenpost repository  
        uses: actions/checkout@v4
        with:
          repository: katzenpost/katzenpost
          path: katzenpost

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Configure podman socket
        run: |
          systemctl --user start podman.socket

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install thinclient dependencies
        run: |
          cd thinclient
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Build and start the mixnet
        run: |
          cd katzenpost/docker && make start wait

      - name: Sleep for a few seconds to allow the mixnet to fully start
        run: sleep 5

      - name: Create symlink for thinclient config
        run: |
          # Create symlink for thinclient config (mixnet configs should exist now)
          cd thinclient
          mkdir -p testdata
          ln -sf ../katzenpost/docker/voting_mixnet/client2/client.toml testdata/thinclient.toml

          # Verify the symlink works
          echo "=== Verifying symlink ==="
          ls -la testdata/
          echo "=== Testing config file exists and is readable ==="
          test -f testdata/thinclient.toml && echo "✅ Config file exists" || echo "❌ Config file missing"
          test -r testdata/thinclient.toml && echo "✅ Config file readable" || echo "❌ Config file not readable"

      - name: Run all Python tests
        run: |
          cd thinclient
          python -m pytest tests/ -vvv --tb=long --log-cli-level=DEBUG --log-cli-format="%(asctime)s [%(levelname)8s] %(name)s: %(message)s" --capture=no

      - name: Stop the mixnet
        if: always()
        run: |
          cd katzenpost/docker && make stop

      - name: Upload testnet state
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mixnet-${{ github.run_id }}-${{ github.job }}
          path: |
            katzenpost/docker/voting_mixnet/*/*.log
