name: Python Unit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-python-unit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Create test config file
        run: |
          mkdir -p testdata
          cp testdata/thinclient.toml testdata/thinclient.toml.bak 2>/dev/null || true
          # Create a minimal config file for unit tests
          cat > testdata/thinclient.toml << 'EOF'
          Network = "tcp"
          Address = "localhost:64331"

          [SphinxGeometry]
            PacketLength = 3082
            NrHops = 5
            HeaderLength = 476
            RoutingInfoLength = 410
            PerHopRoutingInfoLength = 82
            SURBLength = 572
            SphinxPlaintextHeaderLength = 2
            PayloadTagLength = 32
            ForwardPayloadLength = 2574
            UserForwardPayloadLength = 2000
            NextNodeHopLength = 65
            SPRPKeyMaterialLength = 64
            NIKEName = "x25519"
            KEMName = ""

          [PigeonholeGeometry]
            BoxPayloadLength = 1556
            CourierQueryReadLength = 360
            CourierQueryWriteLength = 2000
            CourierQueryReplyReadLength = 1701
            CourierQueryReplyWriteLength = 50
            NIKEName = "CTIDH1024-X25519"
            SignatureSchemeName = "Ed25519"
          EOF

      - name: Run Python unit tests
        run: |
          python -m pytest tests/test_core.py -vvv --tb=long
